title: Comunidade WordPress São Paulo
description: Bem-vindo ao site da comunidade de usuários de WordPress em São Paulo! Aqui você terá acesso aos links e informação necessários para participar das atividades da comunidade.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-autoprefixer
